repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-ast
    -   id: detect-private-key
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/pyupgrade 
    rev: v2.34.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety 
    rev: v1.3.0
    hooks:
    -   id: python-safety-dependencies-check
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black 
