name: Python Black Check
on: [push, pull_request]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
      - run: echo "$(ls)"
      - run: echo "$(pwd)"
      - run: python3 -m pip install -r dev-requirements.txt
      - run: python3 -m black --check --verbose src/
  

